### PR TITLE
Configure security protocol for schema registry  when Kafka security …

### PR DESCRIPTION
**Pull request by geiralund**
…is enabled, e.g.

`val env = KafkaEnvironment(withSecurity = true)`
- Added test: producing and consuming avro messages

### CODE REVIEW

**Comment by geiralund** [comment]
Fixes a bug (?) embedded kafka has both schemaRegistry and withSecurity feature enabled (https://github.com/confluentinc/schema-registry/blob/master/core/src/main/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryConfig.java#L174-L194)

**Comment by ttnesby** [comment]
I simply forgot that option, thank you!

Trong, this is good for me 👍

**Review by tronghn — APPROVED** [review]
LGTM

**Comment by geiralund** [comment]
Great! Thanks!

**Comment by tronghn** [comment]
2.0.1 should now be available on Maven Central

**Pull request merged**
