### PR TITLE
Updated Kotlin to 1.3.11, Kafka to 2.0.1, bump dependencies

### PR DESCRIPTION
**Pull request by geiralund**

### CODE REVIEW

**Comment by ttnesby** [comment]
Good for me :-)

**Comment by tronghn** [comment]
Thank you for your contribution!

You forgot to update line 15 in `build.gradle` (we should probably just migrate the entire build script over to the Kotlin DSL), as well as updating references to experimental coroutines usage.

I'll fix these issues as well as bumping some other dependencies before merging.

**Comment by tronghn** [comment]
Took slightly longer than expected (due to unforseen issues with Travis and staging repositories), but 2.0.2 should now be available on Maven Central.

**Comment by geiralund** [comment]
Great! Thanks a lot!

**Pull request merged**
